name: thumbnailer
description: Plugin that is able to generate thumbnails from files with various mime types. If thumbnail generation is not support for specific mime type, then a fallback icon is returned
version: 2.2.0
homepage: https://github.com/4Q-s-r-o/thumbnailer

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  font_awesome_flutter: ^10.2.1
  pdfx: 
   git:
    url: 'https://github.com/ScerIO/packages.flutter' 
    ref: 'd9e552f65160849026244c7ff8eb537c0a1c8f8e'  
    path: packages/pdfx
  spreadsheet_decoder: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
